version: "2"
run:
  issues-exit-code: 4
  tests: true
  allow-parallel-runners: true
linters:
  #default: all
  disable:
    - asasalint
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - ginkgolinter
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - iface
    - importas
    - ineffassign
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagalign
    - tagliatelle
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usetesting
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl
    - zerologlint
  #settings:
  #  govet:
  #    enable-all: true
  #  staticcheck:
  #    checks:
  #      - -SA*
  #      - all
  exclusions:
    generated: lax
    #presets:
    #  - comments
    #  - common-false-positives
    #  - legacy
    #  - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: 'SA1016:'
    paths:
      - external/
      - third_party$
      - builtin$
      - examples$
issues:
  uniq-by-line: true
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - external/
      - third_party$
      - builtin$
      - examples$
