# https://github.com/golangci/golangci-lint/blob/master/.golangci.example.yml
run:
  #go: "1.23.4"

  # default concurrency is a available CPU number
  #concurrency: 4

  # timeout for analysis, e.g. 30s, 5m, default is 1m
  #timeout: 1m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 4

  # include test files or not, default is true
  tests: true

  allow-parallel-runners: true

  #skip-files:
  #  - ".*\\.my\\.go$"
  #  - lib/bad.go

output:
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  #disable-all: true
  #enable:
  #  - megacheck
  enable-all: true
  disable:
    - cyclop
    - depguard
    - dogsled
    - dupl
    - dupword
    - errorlint
    #- exhaustivestruct
    - forbidigo
    - funlen
    - forcetypeassert
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    #- gocritic
    - goconst
    - gocyclo
    - godox
    - godot
    - gofumpt
    #- golint
    - gomoddirectives
    - goprintffuncname
    - gosec
    - mnd
    #- govet
    #- ifshort
    - interfacebloat
    #- interfacer
    - ineffassign
    - lll
    # 对于类似“添加邮件用户”这样的操作，流程性的代码很多，但都无法省略，
    # 会导致 maintidx 认为代码复杂度太高，因此这里禁用它。
    - maintidx
    #- maligned
    - nakedret
    - nestif
    - nonamedreturns
    #- nosnakecase
    - nosprintfhostport
    - paralleltest
    - prealloc
    #- scopelint
    - tagliatelle
    - testpackage
    - wastedassign
    - wrapcheck
    - wsl
    - tagalign
  fast: true

linters-settings:
  staticcheck:
    checks: ["all", "-SA*"]
  govet:
    enable-all: true

issues:
  uniq-by-line: true
  exclude-rules:
    # Exclude some staticcheck messages
    - linters:
        - staticcheck
      text: "SA1016:"
  exclude-dirs:
    - external/
