CREATE TABLE IF NOT EXISTS system (
    id  INTEGER PRIMARY KEY AUTOINCREMENT,
    k   TEXT NOT NULL DEFAULT '',
    v   TEXT NOT NULL DEFAULT ''
) STRICT;

CREATE UNIQUE INDEX IF NOT EXISTS idx_system_k ON system (k);
