name: Run unittests.
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04

    env:
        GOPRIVATE: github.com/iredmail/*
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-go@v6
        with:
            # Syntax of rc version: '1.26.0-rc.2' (not '1.26rc2')
            #go-version: stable
            go-version: '>=1.26.3'

      - run: git config --global url."https://$GH_ACCESS_TOKEN@github.com/".insteadOf https://github.com/

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --config=$GITHUB_WORKSPACE/.golangci.yml
          version: latest

      - run: make testv

      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           # Syntax of rc version: 1.26rc2
           #go-package: <pattern>
           go-version-input: 1.26.3

    #- name: Gosec
    #  uses: securego/gosec@master
    #  with:
    #    # we let the report trigger content trigger a failure using the GitHub Security features.
    #    # G304 (CWE-22): Potential file inclusion via variable (Confidence: HIGH, Severity: MEDIUM)
    #    #args: '-exclude G304 -no-fail -fmt sarif -out results.sarif ./...'
    #    args: '-no-fail -nosec -quiet -exclude G101,G304,G402,G404 ./internal/... ./cmd/...'
